--
-- nginx.conf 模板
-- 由 generator.lua 渲染后写入 conf/nginx.conf
-- 使用 {{ key }} 占位符，由模板引擎替换为实际值
--

return [=[
# ============================================================
# Auto-generated by apioak from conf/apioak.yaml
# DO NOT EDIT THIS FILE DIRECTLY
# ============================================================

master_process on;

worker_processes {{ worker_processes }};

error_log {{ error_log }} {{ error_log_level }};

events {
    accept_mutex off;
    worker_connections {{ worker_connections }};
}

worker_rlimit_nofile {{ worker_rlimit_nofile }};

worker_shutdown_timeout {{ worker_shutdown_timeout }};

http {
    include {{ mime_types_path }};

    lua_package_path  "$prefix/?.lua;$prefix/?/init.lua;$prefix/lua_modules/share/lua/5.1/?.lua;$prefix/lua_modules/share/lua/5.1/?/init.lua;$prefix/share/lua/5.1/?.lua;$prefix/share/lua/5.1/?/init.lua;/usr/share/lua/5.1/?.lua;;";
    lua_package_cpath "$prefix/lib/lua/5.1/?.so;$prefix/lua_modules/lib/lua/5.1/?.so;$prefix/lua_modules/lib64/lua/5.1/?.so;/usr/lib/lua/5.1/?.so;/usr/lib64/lua/5.1/?.so;;";

    log_format main '$remote_addr\t$http_x_forwarded_for\t$time_iso8601\t$scheme://$http_host\t$request\t$request_length\t'
    '$http_referer\t$http_user_agent\t$connection_requests\t$upstream_cache_status\t$status\t'
    '$request_time\t$upstream_response_time\t$bytes_sent\t$body_bytes_sent\t$server_name\t'
    '$upstream_addr\t$upstream_status\t$request_id\t';

    access_log {{ access_log }} main;

{{ resolver }}

    client_max_body_size {{ client_max_body_size }};

    real_ip_header X-Real-IP;
    set_real_ip_from 127.0.0.1;
    set_real_ip_from unix:;

    more_set_headers 'Server: APIOAK API Gateway';

    lua_code_cache on;

{{ shared_dicts }}

    upstream apioak_backend {
        server 0.0.0.1;
        balancer_by_lua_block {
            apioak.http_balancer()
        }
        keepalive 1024;
    }

    init_by_lua_block {
        apioak = require "apioak.apioak"
        apioak.init()
    }

    init_worker_by_lua_block {
        apioak.init_worker()
    }

{{ admin_server }}

    server {
{{ http_listen }}
{{ https_listen }}

        ssl_certificate      {{ ssl_certificate }};
        ssl_certificate_key  {{ ssl_certificate_key }};
        ssl_session_cache    shared:SSL:10m;
        ssl_session_timeout  10m;

        ssl_protocols        TLSv1.2 TLSv1.3;
        ssl_ciphers          HIGH:!aNULL:!MD5:!kEDH;

        ssl_certificate_by_lua_block {
             apioak.ssl_certificate()
        }

        location / {
            add_header X-Request-Id $request_id;

            access_by_lua_block {
                apioak.http_access()
            }

            header_filter_by_lua_block {
                apioak.http_header_filter()
            }

            body_filter_by_lua_block {
                apioak.http_body_filter()
            }

            log_by_lua_block {
                apioak.http_log()
            }

            set $upstream_scheme             'http';
            set $upstream_host               $host;
            set $upstream_upgrade            '';
            set $upstream_connection         '';
            set $upstream_uri                '';

            proxy_http_version 1.1;
            proxy_set_header   Host              $upstream_host;
            proxy_set_header   Upgrade           $upstream_upgrade;
            proxy_set_header   Connection        $upstream_connection;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Request-Id      $request_id;
            proxy_pass_header  Server;
            proxy_pass_header  Date;
            proxy_pass         $upstream_scheme://apioak_backend$upstream_uri;
        }

        location /apioak/prometheus/metrics {
            content_by_lua 'prometheus:collect()';
        }
    }
}
]=]
